# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_order_get_collection:
    path:   /order/
    defaults:  { _controller: AiselOrderBundle:Admin/Api:getCollection, _format: json }
    methods: [GET]

admin_api_aisel_order_get:
    path:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:get, _format: json }
    methods: [GET]

admin_api_aisel_order_put:
    path:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:put, _format: json }
    methods: [PUT]

admin_api_aisel_order_delete:
    path:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:delete, _format: json }
    methods: [DELETE]

admin_api_aisel_order_post:
    path:   /order/
    defaults:  { _controller: AiselOrderBundle:Admin/Api:post, _format: json }
    methods: [POST]
