# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_order_collection:
    path:  /orders/my
    defaults: { _controller: AiselOrderBundle:ApiOrder:getOrderCollection, _format: json }
    methods: [GET]

api_aisel_order_get:
    path:  /order/{orderId}
    defaults: { _controller: AiselOrderBundle:ApiOrder:getOrder, _format: json }
    methods: [GET]

api_aisel_order_post:
    path:  /{locale}/order
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderSubmit, _format: json }
    methods: [POST]

api_aisel_order_checkout:
    path:  /{locale}/order/checkout
    defaults: { _controller: AiselOrderBundle:ApiCheckout:init, _format: json }
    methods: [GET]
