# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_navigation_get:
    path:   /navigation/{id}
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:get, _format: json }
    methods: [GET]

admin_api_aisel_navigation_get_collection:
    path:   /navigation/
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:getCollection, _format: json }
    methods: [GET]

admin_api_aisel_navigation_get_tree:
    path:   /navigation/tree/
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:getTree, _format: json }
    methods: [GET]

admin_api_aisel_navigation_put:
    path:   /navigation/{id}
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:put, _format: json }
    methods: [PUT]

admin_api_aisel_navigation_post:
    path:   /navigation/
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:post, _format: json }
    methods: [POST]

admin_api_aisel_navigation_delete:
    path:   /navigation/{id}
    defaults:  { _controller: AiselNavigationBundle:Admin/ApiNode:delete, _format: json }
    methods: [DELETE]