# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_navigationmenu:
    path:  /{locale}/navigation/
    defaults: { _controller: AiselNavigationBundle:Api:getTree, _format: json }
    methods: [GET]
