nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Requested-With','Content-Type','Authorization','Location']
            allow_methods: ['POST', 'PUT', 'PATCH', 'OPTIONS', 'GET', 'DELETE']
            allow_credentials: true
            expose_headers: ['location']
            max_age: 3600
