imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: twig.yml }
    - { resource: configs/doctrine.yml }
    - { resource: configs/aisel.yml }
    - { resource: configs/cors.yml }
    - { resource: configs/mailgun.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 0
        name: AISELSESSID
        save_path: /tmp # for Vagrant
#        save_path: %kernel.root_dir%/var/sessions
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
    filters:
        cssrewrite: ~

# Annotations
sensio_framework_extra:
    view:
        annotations: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"

# REST
fos_rest:
    view:
        view_response_listener: 'force'