# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#CRUD
admin_api_aisel_user_get_collection:
    path:   /user/
    defaults:  { _controller: AiselUserBundle:Admin/Api:getCollection, _format: json }
    methods: [GET]

admin_api_aisel_user_get:
    path:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:get, _format: json }
    methods: [GET]

admin_api_aisel_user_put:
    path:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:put, _format: json }
    methods: [PUT]

admin_api_aisel_user_delete:
    path:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:delete, _format: json }
    methods: [DELETE]

admin_api_aisel_user_post:
    path:   /user/
    defaults:  { _controller: AiselUserBundle:Admin/Api:post, _format: json }
    methods: [POST]