# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#Product Node
admin_api_aisel_product_node_get:
    path:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:get, _format: json }
    methods: [GET]

admin_api_aisel_product_node_get_collectiom:
    path:   /product/node/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:getCollection, _format: json }
    methods: [GET]

admin_api_aisel_product_node_get_tree:
    path:   /product/node/tree/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:getTree, _format: json }
    methods: [GET]

admin_api_aisel_product_node_put:
    path:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:put, _format: json }
    methods: [PUT]

admin_api_aisel_product_node_post:
    path:   /product/node/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:post, _format: json }
    methods: [POST]

admin_api_aisel_product_node_delete:
    path:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:delete, _format: json }
    methods: [DELETE]

#Product
admin_api_aisel_product_get:
    path:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:get, _format: json }
    methods: [GET]

admin_api_aisel_product_delete:
    path:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:delete, _format: json }
    methods: [DELETE]

admin_api_aisel_product_put:
    path:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:put, _format: json }
    methods: [PUT]

admin_api_aisel_product_get_collection:
    path:   /product/
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:getCollection, _format: json }
    methods: [GET]

# Reviews
admin_api_aisel_product_review_get:
    path:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:get, _format: json }
    methods: [GET]

admin_api_aisel_product_review_get_collection:
    path:   /product/review/
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:getCollection, _format: json }
    methods: [GET]

admin_api_aisel_product_review_put:
    path:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:put, _format: json }
    methods: [PUT]

admin_api_aisel_product_review_delete:
    path:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:delete, _format: json }
    methods: [DELETE]