# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#Page
seller_api_aisel_page_get_collection:
    path:   /page/
    defaults:  { _controller: AiselPageBundle:Seller/ApiPage:getCollection, _format: json }
    methods: [GET]

seller_api_aisel_page_get:
    path:   /page/{id}
    defaults:  { _controller: AiselPageBundle:Seller/ApiPage:get, _format: json }
    methods: [GET]

seller_api_aisel_page_delete:
    path:   /page/{id}
    defaults:  { _controller: AiselPageBundle:Seller/ApiPage:delete, _format: json }
    methods: [DELETE]

seller_api_aisel_page_put:
    path:   /page/{id}
    defaults:  { _controller: AiselPageBundle:Seller/ApiPage:put, _format: json }
    methods: [PUT]

seller_api_aisel_page_post:
    path:   /page/
    defaults:  { _controller: AiselPageBundle:Seller/ApiPage:post, _format: json }
    methods: [POST]
